services:
  dev:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
      - "8080:8080"
    environment:
      - NODE_ENV=development
    command: sh -c "yarn install && yarn dev"
    stdin_open: true
    tty: true

volumes:
  node_modules:
